export const projects = [
  {
    id: "1",
    title: "Modern Bathroom Renovation",
    category: "Bathroom",
    description: "Complete bathroom renovation with large format tiles and waterproofing",
    fullDescription:
      "This stunning bathroom transformation features premium large format tiles, complete waterproofing solutions, and meticulous attention to detail. The project included floor-to-ceiling tiling, custom shower niche, and heated floor installation.",
    year: "2024",
    location: "Bondi, Sydney",
    mainImage: "/images/14.jpg",
    gallery: [
      "/images/14.jpg",
      "/images/19.jpg",
      "/images/24.jpg",
      "/images/29.jpg",
      "/images/7.jpg",
      "/images/9.jpg",
    ],
  },
  {
    id: "2",
    title: "Kitchen Backsplash",
    category: "Kitchen",
    description: "Contemporary kitchen backsplash with subway tiles",
    fullDescription:
      "A contemporary kitchen update featuring classic white subway tiles arranged in a timeless pattern. The backsplash extends to the ceiling, creating a clean and bright aesthetic that complements the modern kitchen design.",
    year: "2024",
    location: "Mosman, Sydney",
    mainImage: "/images/6.jpg",
    gallery: [
      "/images/6.jpg",
      "/images/11.jpg",
      "/images/16.jpg",
      "/images/21.jpg",
      "/images/26.jpg",
    ],
  },
  {
    id: "3",
    title: "Outdoor Patio",
    category: "Outdoor",
    description: "Large outdoor patio with natural stone tiles",
    fullDescription:
      "Expansive outdoor entertainment area featuring durable natural stone tiles that withstand Sydney's climate. The installation includes proper drainage, leveling, and sealing for longevity and easy maintenance.",
    year: "2024",
    location: "Manly, Sydney",
    mainImage: "/images/10.jpg",
    gallery: [
      "/images/10.jpg",
      "/images/28.jpg",
      "/images/33.jpg",
      "/images/38.jpg",
      "/images/43.jpg",
      "/images/48.jpg",
    ],
  },
  {
    id: "4",
    title: "Herringbone Floor",
    category: "Floor",
    description: "Herringbone pattern floor installation",
    fullDescription:
      "Sophisticated herringbone pattern floor installation using wood-look porcelain tiles. This classic pattern adds visual interest and elegance to the living space while providing the durability of tile.",
    year: "2023",
    location: "Paddington, Sydney",
    mainImage: "/images/14.jpg",
    gallery: [
      "/images/14.jpg",
      "/images/19.jpg",
      "/images/24.jpg",
      "/images/29.jpg",
      "/images/34.jpg",
    ],
  },
  {
    id: "5",
    title: "Master Ensuite",
    category: "Bathroom",
    description: "Luxury ensuite with marble effect tiles",
    fullDescription:
      "High-end master ensuite renovation featuring luxurious marble effect tiles throughout. The project includes a freestanding tub surround, walk-in shower with rainfall head, and heated flooring for ultimate comfort.",
    year: "2023",
    location: "Double Bay, Sydney",
    mainImage: "/images/18.jpg",
    gallery: [
      "/images/18.jpg",
      "/images/23.jpg",
      "/images/27.jpg",
      "/images/31.jpg",
      "/images/35.jpg",
      "/images/39.jpg",
    ],
  },
  {
    id: "6",
    title: "Commercial Lobby",
    category: "Commercial",
    description: "Commercial space floor tiling",
    fullDescription:
      "Large-scale commercial lobby floor installation featuring high-traffic rated porcelain tiles. The project required precise leveling and pattern matching across a 200sqm area, completed on schedule without disrupting building operations.",
    year: "2023",
    location: "Sydney CBD",
    mainImage: "/images/24.jpg",
    gallery: [
      "/images/24.jpg",
      "/images/36.jpg",
      "/images/41.jpg",
      "/images/46.jpg",
      "/images/50.jpg",
    ],
  },
  {
    id: "7",
    title: "Pool Area",
    category: "Outdoor",
    description: "Pool surround with non-slip tiles",
    fullDescription:
      "Safety-focused pool surround installation using premium non-slip tiles. The design balances aesthetics with functionality, creating a beautiful outdoor area that's safe for families while complementing the pool design.",
    year: "2024",
    location: "Vaucluse, Sydney",
    mainImage: "/images/28.jpg",
    gallery: [
      "/images/28.jpg",
      "/images/33.jpg",
      "/images/37.jpg",
      "/images/42.jpg",
      "/images/47.jpg",
      "/images/49.jpg",
    ],
  },
  {
    id: "8",
    title: "Feature Wall",
    category: "Wall",
    description: "Geometric pattern feature wall",
    fullDescription:
      "Eye-catching geometric pattern feature wall installation using mixed finish tiles. This statement piece transforms the living room with its bold design while maintaining the sophisticated aesthetic of the home.",
    year: "2024",
    location: "Surry Hills, Sydney",
    mainImage: "/images/32.jpg",
    gallery: [
      "/images/32.jpg",
      "/images/17.jpg",
      "/images/22.jpg",
      "/images/44.jpg",
      "/images/45.jpg",
    ],
  },
]
