export const projects = [
  {
    id: "1",
    title: "Modern Bathroom Renovation",
    category: "Bathroom",
    description: "Complete bathroom renovation with large format tiles and waterproofing",
    fullDescription:
      "This stunning bathroom transformation features premium large format tiles, complete waterproofing solutions, and meticulous attention to detail. The project included floor-to-ceiling tiling, custom shower niche, and heated floor installation.",
    year: "2024",
    location: "Bondi, Sydney",
    mainImage: "/images/bathroom/1.jpg",
    gallery: [
      "/images/bathroom/1.jpg",
      "/images/bathroom/2.jpg",
      "/images/bathroom/3.jpg",
    ],
  },
  {
    id: "2",
    title: "Kitchen Backsplash",
    category: "Kitchen",
    description: "Contemporary kitchen backsplash with subway tiles",
    fullDescription:
      "A contemporary kitchen update featuring classic white subway tiles arranged in a timeless pattern. The backsplash extends to the ceiling, creating a clean and bright aesthetic that complements the modern kitchen design.",
    year: "2024",
    location: "Mosman, Sydney",
    mainImage: "/images/wall/3.jpg",
    gallery: [
      "/images/wall/4.jpg",
      "/images/wall/1.jpg",
      "/images/wall/2.jpg",
    ],
  },
  {
    id: "3",
    title: "Outdoor Patio",
    category: "Outdoor",
    description: "Large outdoor patio with natural stone tiles",
    fullDescription:
      "Expansive outdoor entertainment area featuring durable natural stone tiles that withstand Sydney's climate. The installation includes proper drainage, leveling, and sealing for longevity and easy maintenance.",
    year: "2024",
    location: "Manly, Sydney",
    mainImage: "/images/outdoor/1.jpg",
    gallery: [
      "/images/outdoor/1.jpg",
      "/images/outdoor/2.jpg",
      "/images/outdoor/3.jpg",
      "/images/outdoor/4.jpg",
      "/images/outdoor/5.jpg",
      "/images/outdoor/6.jpg",
      "/images/outdoor/7.jpg",
      "/images/outdoor/8.jpg",
      "/images/outdoor/9.jpg",
      "/images/outdoor/10.jpg",
      "/images/outdoor/11.jpg",
      "/images/outdoor/12.jpg",
      "/images/outdoor/13.jpg",
      "/images/outdoor/14.jpg",
      "/images/outdoor/15.jpg",
      "/images/outdoor/16.jpg",
      "/images/outdoor/17.jpg",
    ],
  },
  {
    id: "4",
    title: "Herringbone Floor",
    category: "Floor",
    description: "Herringbone pattern floor installation",
    fullDescription:
      "Sophisticated herringbone pattern floor installation using wood-look porcelain tiles. This classic pattern adds visual interest and elegance to the living space while providing the durability of tile.",
    year: "2023",
    location: "Paddington, Sydney",
    mainImage: "/images/floor/1.jpg",
    gallery: [
      "/images/floor/1.jpg",
      "/images/floor/2.jpg",
      "/images/floor/3.jpg",
      "/images/floor/4.jpg",
      "/images/floor/5.jpg",
      "/images/floor/6.jpg",
      "/images/floor/7.jpg",
      "/images/floor/8.jpg",
      "/images/floor/9.jpg",
      "/images/floor/10.jpg",
      "/images/floor/11.jpg",
      "/images/floor/12.jpg",
      "/images/floor/13.jpg",
      "/images/floor/14.jpg",
      "/images/floor/15.jpg",
    ],
  },
  {
    id: "5",
    title: "Master Ensuite",
    category: "Bathroom",
    description: "Luxury ensuite with marble effect tiles",
    fullDescription:
      "High-end master ensuite renovation featuring luxurious marble effect tiles throughout. The project includes a freestanding tub surround, walk-in shower with rainfall head, and heated flooring for ultimate comfort.",
    year: "2023",
    location: "Double Bay, Sydney",
    mainImage: "/images/bathroom/1.jpg",
    gallery: [
      "/images/bathroom/1.jpg",
      "/images/bathroom/2.jpg",
      "/images/bathroom/3.jpg",
    ],
  },
  {
    id: "6",
    title: "Commercial Lobby",
    category: "Commercial",
    description: "Commercial space floor tiling",
    fullDescription:
      "Large-scale commercial lobby floor installation featuring high-traffic rated porcelain tiles. The project required precise leveling and pattern matching across a 200sqm area, completed on schedule without disrupting building operations.",
    year: "2023",
    location: "Sydney CBD",
    mainImage: "/images/24.jpg",
    gallery: [
      "/images/24.jpg",
      "/images/36.jpg",
      "/images/41.jpg",
      "/images/46.jpg",
      "/images/50.jpg",
    ],
  },
  {
    id: "7",
    title: "Pool Area",
    category: "Outdoor",
    description: "Pool surround with non-slip tiles",
    fullDescription:
      "Safety-focused pool surround installation using premium non-slip tiles. The design balances aesthetics with functionality, creating a beautiful outdoor area that's safe for families while complementing the pool design.",
    year: "2024",
    location: "Vaucluse, Sydney",
    mainImage: "/images/pool/1.jpg",
    gallery: [
      "/images/pool/1.jpg",
      "/images/pool/2.jpg",
      "/images/pool/3.jpg",
      "/images/pool/4.jpg",
      "/images/pool/5.jpg",
    ],
  },
  {
    id: "8",
    title: "Feature Wall",
    category: "Wall",
    description: "Geometric pattern feature wall",
    fullDescription:
      "Eye-catching geometric pattern feature wall installation using mixed finish tiles. This statement piece transforms the living room with its bold design while maintaining the sophisticated aesthetic of the home.",
    year: "2024",
    location: "Surry Hills, Sydney",
    mainImage: "/images/wall/1.jpg",
    gallery: [
      "/images/wall/1.jpg",
      "/images/wall/2.jpg",
      "/images/wall/3.jpg",
      "/images/wall/4.jpg",
    ],
  },
]
